name: Build and Test
on: ["push"]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install, test and build
        uses: actions/setup-node@v1
        with:
          always-auth: false
          node-version: 13.x
      - run: npm install
      - run: npm run test
        env:
          CI: true
      - run: npm run build 
